services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    entrypoint: ["apache2-foreground"]
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: docsfinder
      DB_USERNAME: docsfinder_user
      DB_PASSWORD: docsfinder_password
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: docsfinder
      POSTGRES_USER: docsfinder_user
      POSTGRES_PASSWORD: docsfinder_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: